const dogs = [
  {
    origin: ["Deutschland", "Frankreich"],
    fci_no: 186,
    name: "Affenpinscher",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/04/shutterstock_445018054-Kopie-430x430.jpg",
    height: [25, 30],
    weight: [4, 6],
    furLength: 2,
    lifeExpectancy: [12, 14],
    typeOfBreed: ["Begleithund"],
    activity: 35,
    personality: [
      "verspielt",
      "neugierig",
      "lebenslustig",
      "stur",
      "aktiv",
      "abenteuerlustig",
    ],
  },
  {
    origin: ["USA"],
    fci_no: null,
    name: "American Pitbull Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_287024849-Kopie-430x430.jpg",
    height: [43, 53],
    weight: [14, 30],
    furLength: null,
    lifeExpectancy: [8, 15],
    typeOfBreed: ["Familienhund", "Wachhund"],
    activity: 40,
    personality: [
      "intelligent",
      "anhänglich",
      "freundlich",
      "stur",
      "loyal",
      "clownhaft",
      "gehorsam",
      "durchsetzungsstark",
      "sanftmütig",
      "tapfer",
    ],
  },
  {
    origin: ["Österreich"],
    fci_no: 254,
    name: "Alpenländische Dachsbracke",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/04/shutterstock_1702569346-Kopie-430x430.jpg",
    height: [34, 42],
    weight: [16, 18],
    furLength: null,
    lifeExpectancy: [12, 14],
    typeOfBreed: ["Jagdhund"],
    activity: 40,
    personality: ["arbeitswillig", "freundlich", "mutig", "treu"],
  },
  {
    origin: ["Schweiz"],
    fci_no: 46,
    name: "Appenzeller Sennenhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/04/shutterstock_1925631671-Kopie-430x430.jpg",
    height: [47, 58],
    weight: [50, 56],
    furLength: 1,
    lifeExpectancy: [12, 14],
    typeOfBreed: ["Familienhund"],
    activity: 40,
    personality: [
      "selbstsicher",
      "zuverlässig",
      "energisch",
      "lebendig",
      "furchtlos",
    ],
  },
  {
    origin: ["USA"],
    fci_no: 243,
    name: "Alaskan Malamute",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/04/shutterstock_1803184699_komp-430x430.jpg",
    height: [56, 66],
    weight: [32, 43],
    furLength: 1,
    lifeExpectancy: [10, 12],
    typeOfBreed: ["Begleithund"],
    activity: 45,
    personality: [
      "verspielt",
      "freundlich",
      "anhänglich",
      "hingebungsvoll",
      "loyal",
      "würdevoll",
    ],
  },
  {
    origin: ["USA"],
    fci_no: 286,
    name: "American Staffordshire Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/07/American-Staffordshire-Terrier_553222033-430x430.jpg",
    height: [43, 48],
    weight: [18, 32],
    furLength: 1,
    lifeExpectancy: [12, 16],
    typeOfBreed: ["Begleithund"],
    activity: 40,
    personality: [
      "freundlich",
      "loyal",
      "beharrlich",
      "hingebungsvoll",
      "aufmerksam",
      "tapfer",
    ],
  },
  {
    origin: ["Afghanistan"],
    fci_no: 228,
    name: "Afghanischer Windhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_650128147-komprimiert-430x430.jpg",
    height: [60, 74],
    weight: [26, 34],
    furLength: 3,
    lifeExpectancy: [12, 14],
    typeOfBreed: ["Begleithund"],
    activity: 45,
    personality: [
      "zurückhaltend",
      "würdevoll",
      "glücklich",
      "eigenständig",
      "clownhaft",
    ],
  },
  {
    origin: ["Japan"],
    fci_no: 255,
    name: "Akita",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/shutterstock_265439057-komprimiert-430x430.jpg",
    height: [58, 70],
    weight: [32, 59],
    furLength: 3,
    lifeExpectancy: [10, 12],
    typeOfBreed: ["Wachhund"],
    activity: 35,
    personality: [
      "intelligent",
      "treu",
      "loyal",
      "stur",
      "gelassen",
      "aufgeschlossen",
      "tapfer",
    ],
  },
  {
    origin: ["USA"],
    fci_no: 342,
    name: "Australian Shepherd",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/06/shutterstock_416466661-430x430.jpg",
    height: [46, 58],
    weight: [16, 32],
    furLength: 3,
    lifeExpectancy: [13, 15],
    typeOfBreed: ["Hütehund"],
    activity: 50,
    personality: [
      "intelligent",
      "anhänglich",
      "freundlich",
      "aktiv",
      "beschützend",
    ],
  },
  {
    origin: ["Großbritannien"],
    fci_no: 7,
    name: "Airedale Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/04/shutterstock_401718178-komprimiert-430x430.jpg",
    height: [56, 61],
    weight: [18, 29],
    furLength: 1,
    lifeExpectancy: [10, 12],
    typeOfBreed: ["Jagdhund"],
    activity: 45,
    personality: [
      "intelligent",
      "freundlich",
      "kontaktfreudig",
      "konzentriert",
      "selbstbewusst",
      "tapfer",
    ],
  },
  {
    origin: ["Belgien"],
    fci_no: 84,
    name: "Bloodhound",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/07/shutterstock_1113495818-Kopie-430x430.jpg",
    height: [58, 69],
    weight: [0, 0],
    furLength: 1,
    lifeExpectancy: [10, 12],
    typeOfBreed: ["Polizeihund"],
    activity: 40,
    personality: ["anhänglich", "stur", "ausgeglichen", "sanftmütig"],
  },
  {
    origin: ["Italien"],
    fci_no: 194,
    name: "Bergamasker",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_65637454-Kopie-430x430.jpg",
    height: [54, 62],
    weight: [26, 38],
    furLength: 3,
    lifeExpectancy: [13, 15],
    typeOfBreed: ["Hütehund"],
    activity: 45,
    personality: ["intelligent", "zielstrebig", "wachsam", "geduldig"],
  },
];
