const dogs = [

  {
    origin: ['x','y'],
    fci_no: null,
    name: "Border Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/shutterstock_1464454034_komp-430x430.jpg",
    height: ["28", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: ["Jagdhund"],
    activity: 45,
    personality: ["aktiv", "freundlich", "intelligent", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bologneser",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/shutterstock_626156432_komp-430x430.jpg",
    height: ["20", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 20,
    personality: ["anhänglich", "gutmütig", "verschmust", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bichon Frisé",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/iStock-160987733-430x430.jpg",
    height: ["23", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["aktiv", "freundlich", "intelligent", "kinderlieb"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Belgischer Schäferhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/04/shutterstock_138940277_Kopie-430x430.jpg",
    height: ["58", "62"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 50,
    personality: ["aktiv", "anhänglich", "lebhaft", "lernwillig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Border Collie",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_376523338-430x430.jpg",
    height: ["50", "53"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 50,
    personality: ["aktiv", "intelligent", "kinderlieb", "lernwillig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Beagle",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/02/shutterstock_222861379-430x430.jpg",
    height: ["33", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["freundlich", "lebhaft", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Berner Sennenhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_128176703-430x430.jpg",
    height: ["57", "70"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 35,
    personality: ["gutmütig", "selbstbewusst", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bullterrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_696633640-430x430.jpg",
    height: ["45", "55"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 40,
    personality: ["anhänglich", "ausgeglichen", "lebhaft", "mutig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Briard",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/03/shutterstock_551475355-1-1-430x430.jpg",
    height: ["56", "68"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 40,
    personality: ["anhänglich", "kinderlieb", "lebhaft", "liebevoll"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bernhardiner",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/shutterstock_539843389-komprimiert-430x430.jpg",
    height: ["65", "90"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 20,
    personality: ["ausgeglichen", "freundlich", "gutmütig", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bearded Collie",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_637931764-komprimiert-430x430.jpg",
    height: ["51", "56"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 40,
    personality: ["aufmerksam", "intelligent", "lebhaft", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basenji",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/Basenji_520544230-komprimiert-430x430.jpg",
    height: ["40", "43"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["intelligent", "liebevoll", "selbstbewusst", "willensstark"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bordeaux Dogge",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_116089669-1-1-430x430.jpg",
    height: ["58", "68"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 20,
    personality: ["ausgeglichen", "freundlich", "gutmütig", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basset Hound",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_247455631-komprimiert-430x430.jpg",
    height: ["33", "38"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 35,
    personality: ["anhänglich", "ausgeglichen", "treu", "willensstark"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bullmastiff",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/12/Bullmastiff-stehend-430x430.jpg",
    height: ["61", "69"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 35,
    personality: ["intelligent", "lebhaft", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bobtail (Old English Sheepdog)",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_382239544-komprimiert-430x430.jpg",
    height: ["56", "61"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 40,
    personality: ["ausgeglichen", "kinderlieb", "treu", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Boston Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_1195591732-komprimiert-430x430.jpg",
    height: ["36", "42"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 35,
    personality: ["aktiv", "freundlich", "intelligent", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Pinscher",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_1100668127-430x430.jpg",
    height: ["45", "50"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: [
      "aktiv",
      "intelligent",
      "selbstbewusst",
      "verschmust",
      "verspielt",
      "wachsam",
    ],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dackel",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/Rauhaardackel_iStock-858143422-430x430.jpg",
    height: ["20", "26"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["arbeitswillig", "intelligent", "mutig", "willensstark"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutsche Dogge",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/07/Deutsche-Dogge_243209011-430x430.jpg",
    height: ["72", "86"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 40,
    personality: ["anhänglich", "freundlich", "kinderlieb", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dobermann",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/10/Dobermann_673893031-430x430.jpg",
    height: ["63", "72"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 40,
    personality: ["anhänglich", "arbeitswillig", "ausgeglichen", "mutig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Boxer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/05/shutterstock_232556533-komprimiert-430x430.jpg",
    height: ["53", "63"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 40,
    personality: ["intelligent", "liebevoll", "verspielt", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dalmatiner",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/07/Dalmatiner_162655121-430x430.jpg",
    height: ["54", "62"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 50,
    personality: ["aktiv", "kinderlieb", "liebevoll", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Schäferhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/shutterstock_296346053-1-430x430.jpg",
    height: ["55", "65"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 45,
    personality: ["arbeitswillig", "intelligent", "selbstbewusst", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dogo Argentino",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/12/shutterstock_386096602-430x430.jpg",
    height: ["60", "68"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["freundlich", "selbstbewusst", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutsch Drahthaar",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/shutterstock_1112510438-komprimiert-430x430.jpg",
    height: ["57", "68"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 50,
    personality: ["arbeitswillig", "gehorsam", "mutig", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Eurasier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/shutterstock_1945447228-Kopie-430x430.jpg",
    height: ["48", "60"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 40,
    personality: ["anhänglich", "ausgeglichen", "selbstbewusst", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Englische Bulldogge",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_1202703667-komprimiert-430x430.jpg",
    height: ["31", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 20,
    personality: ["kinderlieb", "liebevoll", "mutig", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "English Pointer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/12/shutterstock_663268522-komprimiert-430x430.jpg",
    height: ["61", "69"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 45,
    personality: ["arbeitswillig", "ausgeglichen", "freundlich", "lernwillig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "English Cocker Spaniel",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/English-Cocker-Spaniel_109129094-430x430.jpg",
    height: ["38", "41"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["anhänglich", "freundlich", "gehorsam", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Foxterrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_692745586-komprimiert-430x430.jpg",
    height: ["35", "39"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 45,
    personality: ["aufmerksam", "freundlich", "lebhaft", "mutig"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Französische Bulldogge",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/05/Fraz%C3%B6sische-Bulldogge_333010346-430x430.jpg",
    height: ["24", "35"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["freundlich", "gutmütig", "liebevoll", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Gordon Setter",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/03/shutterstock_143624941-komprimiert-430x430.jpg",
    height: ["62", "66"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 45,
    personality: ["ausgeglichen", "freundlich", "intelligent", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Golden Retriever",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/05/shutterstock_246054700-430x430.jpg",
    height: ["51", "56"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Blindenhund",
    activity: 40,
    personality: ["aktiv", "freundlich", "intelligent", "kinderlieb"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Havaneser",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/03/shutterstock_555561031-komprimiert-430x430.jpg",
    height: ["23", "27"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 25,
    personality: ["gutmütig", "kinderlieb", "lebhaft", "liebevoll"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Holländischer Schäferhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_663698911-komprimiert-1-430x430.jpg",
    height: ["55", "62"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 50,
    personality: ["aktiv", "arbeitswillig", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hovawart",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/11/shutterstock_640646005-430x430.jpg",
    height: ["58", "70"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 45,
    personality: ["arbeitswillig", "ausgeglichen", "selbstbewusst", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irish Wolfhound",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/02/shutterstock_301957253-komprimiert-430x430.jpg",
    height: ["71", "86"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 50,
    personality: ["ausgeglichen", "freundlich", "gutmütig", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Jack Russell Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_651132271-1-430x430.jpg",
    height: ["25", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["freundlich", "intelligent", "lebhaft", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Komondor",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_454303438-Kopie-430x430.jpg",
    height: ["70", "80"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 20,
    personality: ["ausgeglichen", "gehorsam", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kangal",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/iStock-1048194302-komprimiert-430x430.jpg",
    height: ["71", "81"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 45,
    personality: ["ausgeglichen", "intelligent", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kooikerhondje",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_350733329-komprimiert-430x430.jpg",
    height: ["38", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 35,
    personality: ["aktiv", "ausgeglichen", "gehorsam", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kleiner Münsterländer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/04/shutterstock_42078781-komprimiert-430x430.jpg",
    height: ["48", "56"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 45,
    personality: ["ausgeglichen", "freundlich", "lernwillig", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kleinspitz",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/iStock-873854014-430x430.jpg",
    height: ["23", "28"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 25,
    personality: ["anhänglich", "aufmerksam", "lebhaft", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Laika",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/07/shutterstock_623883086-430x430.jpg",
    height: ["50", "63"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 50,
    personality: ["aktiv", "ausgeglichen", "lebhaft", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Lhasa Apso",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_630314351-Kopie-430x430.jpg",
    height: ["23", "25"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 40,
    personality: ["aufmerksam", "freundlich", "lebhaft", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Lagotto Romagnolo",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_1121969561-Kopie-430x430.jpg",
    height: ["41", "48"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 40,
    personality: ["arbeitswillig", "gehorsam", "intelligent", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Labrador Retriever",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/06/shutterstock_126021596-430x430.jpg",
    height: ["54", "57"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Blindenhund",
    activity: 40,
    personality: ["kinderlieb", "liebevoll", "sensibel", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Leonberger",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/03/shutterstock_1033151017-komprimiert-430x430.jpg",
    height: ["65", "80"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["gutmütig", "kinderlieb", "liebevoll", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mastiff",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_85034053-Kopie-430x430.jpg",
    height: ["70", "90"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 20,
    personality: ["ausgeglichen", "mutig", "treu", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mops",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/02/shutterstock_335260598-1-430x430.jpg",
    height: ["25", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["ausgeglichen", "freundlich", "kinderlieb", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Magyar Vizsla",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_575434099-2-1-430x430.jpg",
    height: ["54", "64"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 45,
    personality: ["ausgeglichen", "freundlich", "lebhaft", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Malinois",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/03/shutterstock_1294947628-komprimiert-430x430.jpg",
    height: ["56", "66"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 50,
    personality: ["aktiv", "freundlich", "mutig", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Malteser",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/11/shutterstock_1101586751-komprimiert-430x430.jpg",
    height: ["20", "25"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 25,
    personality: ["anhänglich", "liebevoll", "selbstbewusst", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mittelspitz",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_240202939-komprimiert-430x430.jpg",
    height: ["30", "38"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 25,
    personality: ["anhänglich", "aufmerksam", "intelligent", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Miniature Bullterrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_144645440-430x430.jpg",
    height: ["25", "36"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 40,
    personality: ["anhänglich", "ausgeglichen", "mutig", "verspielt"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Norfolk Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/07/shutterstock_1213451051-430x430.jpg",
    height: ["23", "25"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 40,
    personality: ["aktiv", "freundlich", "liebevoll", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Neufundländer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_589527410-430x430.jpg",
    height: ["63", "71"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["freundlich", "gutmütig", "lebhaft", "liebevoll"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Otterhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/07/shutterstock_6820696331-430x430.jpg",
    height: ["61", "69"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 40,
    personality: ["aktiv", "freundlich", "kinderlieb"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Old English Bulldog",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/shutterstock_250302700-Kopie-430x430.jpg",
    height: ["40", "51"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 40,
    personality: ["-"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pharaonenhund",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/08/shutterstock_12133146191-430x430.jpg",
    height: ["53", "64"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 50,
    personality: ["freundlich", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pekingese",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_1138694957-komprimiert-430x430.jpg",
    height: ["15", "25"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 15,
    personality: ["ausgeglichen", "freundlich", "mutig", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Parson Russell Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/04/shutterstock_1055266865-komprimiert-430x430.jpg",
    height: ["31", "36"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 35,
    personality: ["aktiv", "arbeitswillig", "intelligent", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pudel",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/11/Pudel_676664635-430x430.jpg",
    height: ["24", "60"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 35,
    personality: ["intelligent", "lernwillig", "liebevoll", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Rhodesian Ridgeback",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/01/shutterstock_115737610-1-430x430.jpg",
    height: ["61", "69"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 45,
    personality: ["aktiv", "intelligent", "liebevoll", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Rottweiler",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/10/Rottweiler-Hund-Mischlingshund-iStock-163524069-2-430x430.jpg",
    height: ["56", "68"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Polizeihund",
    activity: 40,
    personality: ["anhänglich", "gehorsam", "kinderlieb", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Riesenschnauzer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/02/shutterstock_1225017208-komprimiert-430x430.jpg",
    height: ["60", "70"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Wachhund",
    activity: 45,
    personality: ["anhänglich", "ausgeglichen", "selbstbewusst", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shar Pei",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/05/shutterstock_1277897209-Kopie-430x430.jpg",
    height: ["46", "51"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 20,
    personality: ["ausgeglichen", "sensibel", "willensstark"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shih Tzu",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/12/shutterstock_261443393-komprimiert-430x430.jpg",
    height: ["25", "27"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 25,
    personality: ["anhänglich", "freundlich", "intelligent"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Staffordshire Bullterrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/11/Bullterrier_268525913-430x430.jpg",
    height: ["35", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 40,
    personality: ["intelligent", "liebevoll", "mutig", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shiba Inu",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_249195868-komprimiert-430x430.jpg",
    height: ["37", "40"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 40,
    personality: ["anhänglich", "intelligent", "lebhaft", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Siberian Husky",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_345091346-komprimiert-430x430.jpg",
    height: ["50", "60"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 50,
    personality: ["aufmerksam", "freundlich", "verspielt", "willensstark"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shetland Sheepdog",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/02/shutterstock_191573639-komprimiert-430x430.jpg",
    height: ["33", "41"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 50,
    personality: ["intelligent", "kinderlieb", "liebevoll", "sensibel"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Samojede",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_721159402-1-430x430.jpg",
    height: ["50", "60"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 40,
    personality: ["anhänglich", "freundlich", "lebhaft"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tibet Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/12/shutterstock_622579874-430x430.jpg",
    height: ["30", "41"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 35,
    personality: ["aktiv", "intelligent", "liebevoll", "selbstbewusst"],
  },
  
  {
    origin: null,
    fci_no: null,
    name: "Weimaraner",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/03/shutterstock_300817325-komprimiert-430x430.jpg",
    height: ["57", "70"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Jagdhund",
    activity: 50,
    personality: ["aktiv", "arbeitswillig", "intelligent", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Welsh Corgi",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2019/01/shutterstock_1195630861-komprimiert-430x430.jpg",
    height: ["25", "31"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Hütehund",
    activity: 35,
    personality: ["arbeitswillig", "kinderlieb", "lebhaft", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "West Highland White Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2017/11/shutterstock_150831518-430x430.jpg",
    height: ["25", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["ausgeglichen", "gutmütig", "kinderlieb", "wachsam"],
  },

  {
    origin: null,
    fci_no: null,
    name: "Yorkshire Terrier",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/03/shutterstock_547062616-1-430x430.jpg",
    height: ["18", "23"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["intelligent", "lebhaft", "mutig", "selbstbewusst"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Zwergschnauzer",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2021/06/shutterstock_1836759934-430x430.jpg",
    height: ["35", "34"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 50,
    personality: ["freundlich", "lernwillig", "verschmust", "wachsam"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Zwergpinscher",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/12/shutterstock_1210631812-komprimiert-430x430.jpg",
    height: ["25", "30"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Begleithund",
    activity: 45,
    personality: ["freundlich", "intelligent", "lernwillig", "treu"],
  },
  {
    origin: null,
    fci_no: null,
    name: "Zwergspitz",
    img: "https://mediafiles.mein-haustier.de/wp-content/uploads/2018/12/shutterstock_1119342971-1-1-430x430.jpg",
    height: ["18", "22"],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: "Familienhund",
    activity: 30,
    personality: ["anhänglich", "aufmerksam", "intelligent", "lebhaft"],
  },

  {
    origin: null,
    fci_no: null,
    name: "Aidi",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Airedale-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Akbash",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Akita Inu",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Altdänischer Vorstehhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "American Bulldog",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "American Staghound",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "American Toy Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "American Water Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Amerikanischer Cocker Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Amerikanischer Cockerspaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Amerikanischer Pit-Bullterrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Australian Cattle Dog",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Australian Kelpie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Australian Silky Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Australian Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Australischer Treibhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Azawakh",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Balearen Laufhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Barbet",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Barsoi",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basset Artésien-Normand",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basset Bleu de Gascogne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basset Fauve de Bretagne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Basset fauve de Bretagne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bayerischer Gebirgsschweisshund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Beauceron",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bedlington Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bedlington-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bergamasker Hirtenhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Berger Picard",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Berger de Pyrénées",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Berger de Pyrénées Langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bichon à poil Frisé",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bichon/Yorkie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Black and Tan Coonhound",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bobtail",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Boerboel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bolonka Zwetna",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bordeauxdogge",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bouvier Des Flandres",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bouvier des Flandres",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Boxer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Brabancon",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bracco Italiano",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Braque Francais des Pyrénées",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Braque d´Auvergne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Brasilianischer Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Briard (Berger de Brie)",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bull Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bull-Boxer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Bulldog",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ca de Bou",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cairn Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cairn-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cane Corso",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cao da Serra da Estrela",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cao da Serra de Aires",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cao de Agua Portugues",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cao de agua Português",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Catahoula Leopard Dog",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cavalier King Charles Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ceský Fousek",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ceský Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chesapeake Bay Retriever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chihuahua",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chihuahua kurzhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chihuahua langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chinesischer Schopfhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chinesischer Schopfhund Hairless-Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chinesischer Schopfhund Powderpuff-Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chow Chow",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Chow-Chow",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cirneco dell´ Etna",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Clumber Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Clumber-Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Cockerpoo",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Collie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Coton de Tuléar",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Curly Coated Retriever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Curly-Coated Retriever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dandie Dinmont Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deerhound",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutsch Kurzhaar",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutsch Langhaar",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Jagdterrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Schäferhund Brauner langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Schäferhund Cremefarbener langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Schäferhund Schwarzer langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Wachtelhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Deutscher Wolfsspitz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Drever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Dänischer Bauernhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Englischer Cocker Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Englischer Setter",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Englischer Springer Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "English Setter",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "English Springer Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "English Toy Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Entlebucher Sennenhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Epagneul Breton",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Field Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Fila Brasileiro",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Finnischer Lapphund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Finnischer Spitz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Flat Coated Retriever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Foxhound",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Foxterrier Drahthaar",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Foxterrier Glatthaar",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Galgo Espanol",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Glen of Imaal Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Gos d´Atura Català",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grand Basset Griffon Vendéen",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grand Bleu de Gascogne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Greyhound",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Griffon Belge",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Griffon Bruxellois",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Griffon Fauve de Bretagne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Griffon Nivernais",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Griffon á Poil Dur",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Groenendael",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grosser Münsterländer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grosser Schweizer Sennenhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grosspudel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Grönlandhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hamiltonstövare",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hannoverscher Schweisshund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hollandse Herdershond",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hollandse Herdershond Langhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Hollandse Herdershond Rauhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Illyrischer Schäferhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irischer Soft Coated Wheaten Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irish Red Setter",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irish Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irish Water Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Irish red-and-white Setter",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Islandhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Italienisches Windspiel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Jack-Russell-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Japan Chin",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Japan Spitz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Japanischer Akita",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Japanischer Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Jura-Laufhund (Bruno)",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kanaanhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kanarische Dogge",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kaukasischer Schäferhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Keeshond",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kerry Blue Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "King Charles Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kromfohrländer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kurzhaarcollie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kurzhaardackel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kurzhaariger Ungarischer Vorstehhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kuvasz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Kyi Leo",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Labradoodle",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Laekenois",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Lakeland Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Landseer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Langhaarcollie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Langhaardackel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Lappländer Rentierhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Lucas-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Luzerner Laufhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Löwchen",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Manchester-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Maremmaner Hirtenhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Maremmen Abruzzen Schäferhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mastin Espanol",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mastino Napoletano",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mexikanischer Nackthund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Miniatur Bullterrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Miniature American Shepherd",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Miniature Bull Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mittelasiatischer Schäferhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mittelasiatischer Schäferhund Kurzhaariger Schlag",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Mudi",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Nederlandse Kooikerhondje",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Norfolk-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Norwegischer Elchhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Norwegischer Lundehund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Norwich Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Nova Scotia Duck Tolling Retriever",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Old English Sheepdog",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Olde English Bulldogge",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ostsibirischer Laika",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Papillon",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Parson-Russell-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Patterdale-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Perdigueiro Portugues",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Perro de Agua Espanol",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Peruvian Inca Orchid",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Petit Basset Griffon Vendéen",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Petit Basset griffon vendéen",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Petit Bleu de Gascogne",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Phalene",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Plummer-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Podengo Portugueso Pequeno",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pointer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Polnische Bracke",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Polnischer Niederungshütehund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Polski Owczarek Podhalanski",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Porcelaine",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Praszký Krysavik",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pudelpointer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Puli",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pumi",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pyrenäen-Berghund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pyrenäenberghund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Pyrenäenhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Rampur-Windhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Rauhhaardackel (Zwergdackel)",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Russisch-Europäischer Laika",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Russischer Schwarzer Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Saarlooswolfhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sabueso Espanol",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Saluki",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schapendoes",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schipperke",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schnauzer",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schottischer Jagdhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schwarzer Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Schwedischer Lapphund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Scottish Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sealyham Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sealyham-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Segugio Italiano (Kurzhaar)",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sheltie",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shikoku",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Shiloh Shepherd",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Skye Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sloughi",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Slovensky Cuvac",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Slovensky Kopov",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Slowakischer Rauhbart",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Soft Coated Wheaten Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Spinone Italiano",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Staffordshire Bull Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Steirische Rauhhaarbracke",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sussex Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Sussex-Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Südrussischer Owtscharka",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Teckel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tervueren",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Thai Ridgeback",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tibet-Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tibet-Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tibetdogge",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tibetischer Kyi Apso",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tosa",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Toy-Pudel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Tschechoslowakischer Wolfhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ungarische Bracke",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ungarischer Vizsla",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Ungarischer Windhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Volpino Italiano",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Västgötaspets",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Weißer Schweizer Schäferhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Welsh Corgi Cardigan",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Welsh Corgi Pembroke",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Welsh Springer Spaniel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Welsh Terrier",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Westgotenspitz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Westsibirischer Laika",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Whippet",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Windhund",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Wolfsspitz",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Wäller",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },
  {
    origin: null,
    fci_no: null,
    name: "Zwergpudel",
    img: null,
    height: [0, 0],
    weight: [0, 0],
    furLength: null,
    lifeExpectancy: [0, 0],
    typeOfBreed: [],
    activity: null,
    personality: [],
  },

];

// let i = 1;
// dogs.forEach(dog => {
//     console.log(`${i} - ${dog.name}`);
//     i++;
// });


const sortDogs = dogs.sort(function(a, b) {
    return a.name > b.name ? 1:-1;
});

sortDogs.forEach(d => console.log(d.name))